spring.application.name=Mini_Coderspace

spring.datasource.url=jdbc:postgresql://localhost:5432/coderspace-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update